spring:
  # 数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.245.176:3306/gemini
    username: root
    password: hisense
    initialSize: 5
    minIdle: 2
    maxActive: 8
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
  # redis
#  redis:
#    database: 1
#    host: 127.0.0.1
#    port: 6379
#    password:
#    pool.max-idle: 8
#    pool.min-idle: 0
#    pool.max-active: 8
#    pool.max-wait: -1
#    timeout: 5000
  # thymeleaf模板配置
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/page/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

  # mvc
  mvc:
    static-path-pattern: /resources/**

logging:
  level:
    org:
      springframework:
        web: DEBUG